### ISSUE TITLE
I got this issue today trying to install Lemmer, crashed my whole project

### ISSUE THREAD

**Issue by Prosquid1** [silentrob/lemmer#5]
.pipe(tar.Extract({ path: __dirname }))

TypeError: tar.Extract is not a function
    at extractTarball (/app/node_modules/lemmer/node_modules/wndb-with-exceptions/unpack.js:52:15)
    at Object.<anonymous> (/app/node_modules/lemmer/node_modules/wndb-with-exceptions/unpack.js:58:1)
    at Module._compile (module.js:409:26)

**Comment by sockery** [comment]
Hey, I just had encountered the same issue. If you update your dependency version to ^0.2.1, the issue should be resolved.

**Comment by bensalilijames** [comment]
Should be fixed with the update in `wndb-with-exceptions`.
